### ISSUE TITLE
add 'stop-pool!' function

### ISSUE THREAD

**Issue by KevinCorcoran** [overtone/at-at#13]
I'd like a way to shutdown a thread pool without also resetting it.  Currently, I have to just call `stop-and-reset-pool!`, which shuts down the the pool (good) but also creates a new thread pool, which I don't actually want to happen, since I'm calling this in the context of shutting down the entire application.

**Comment by KevinCorcoran** [comment]
Ah, just realized that this is pretty close to #9 , although I'd like to just pass-in a `pool` and not a `pool-info`.

**Comment by codeasone** [comment]
+1
