### ISSUE TITLE
Expose exceptions in scheduled functions

### ISSUE THREAD

**Issue by dmac** [overtone/at-at#7]
At the moment, if a scheduled function throws an exception it fails silently.

``` clojure
(def tp (at-at/mk-pool))

(defn -main [& args]
  (at-at/every 1000 #(throw (Exception. "You'll never see me"))
               tp :desc "My job")
  (Thread/sleep 3000)
  (System/exit 0))
```

This can be confusing and make it appear that the function isn't running.

Ideally I'd like to see output like this:

```
at-at task [1][RECUR] "My job" threw java.lang.Exception: You'll never see me
at-at task [1][RECUR] "My job" threw java.lang.Exception: You'll never see me
at-at task [1][RECUR] "My job" threw java.lang.Exception: You'll never see me
```

Another option would be to fail fast by re-raising the exception and crashing the program, which would at least indicate that the user needs to handle an error case.

**Comment by davidrupp** [comment]
Bump.

**Comment by adamneilson** [comment]
Bump +1

**Comment by mjg123** [comment]
AIUI any exception on a background thread will cause the thread to die silently - this isn't specific to at-at.  There's an approach you can use here: https://stuartsierra.com/2015/05/27/clojure-uncaught-exceptions

**Comment by kenfehling** [comment]
@mjg123 I tried using the uncaught exception handler from that article but nothing still gets through. Do you have an example of how to use it with at-at?

**Comment by kenfehling** [comment]
@mjg123 I tried using the uncaught exception handler from that article but still no errors are getting through. Do you have an example of using it with at-at?
